name: Release Docker Image

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
  KANIKO_CACHE_ARGS: "--cache=true --cache-copy-layers=true --cache-ttl=24h"

jobs:
  build-to-docker-hub:
    runs-on: home-use-base-image
    environment:
      name: dockerhub
      url: https://hub.docker.com/repository/docker/karandash8/home-use-base-image
    container:
      image: gcr.io/kaniko-project/executor:v1.20.0-debug
    permissions:
      contents: read

    steps:
      - name: Build and Push Image to docker registry with kaniko
        env:
          DOCKER_IMAGE_NAME: "karandash8/home-use-base-image:latest"
        run: |
          cat <<EOF > /kaniko/.docker/config.json
          {
            "auths": {
              "https://index.docker.io/v1/": {
                "auth": "$(echo -n "${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }}" | base64 )"
              }
            }
          }
          EOF

          /kaniko/executor --dockerfile="./Dockerfile" \
            --context="${{ github.repositoryUrl }}#${{ github.ref }}#${{ github.sha }}"  \
            --destination="$DOCKER_IMAGE_NAME" \
            ${{ env.KANIKO_CACHE_ARGS }} \
            --push-retry 5
